# Generated by Django 3.1.4 on 2021-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210203_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to='authentication.Post'),
        ),
    ]
